version: "3.7"

services :
  nginx:
    container_name: nginx
    networks:
    - inception
    volumes:
    - wordpress:/var/www/wordpress
    depends_on:
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    expose:
    - "3306"
    restart: always
  
  wordpress:
    container_name: wordpress
    networks: 
    - inception
    volumes:
    - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on :
    - mariadb
    restart: always
    
volumes:
  wordpress:
    driver : local
    driver_opts:
      type: none
      device: /home/ramsy/data/wordpress
      o: bind 
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ramsy/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge

