version: "3.7"

services :
  nginx:
    container_name: nginx
    image: nginx
    networks:
    - inception
    volumes:
    - wordpress:/var/www/wordpress
    depends_on:
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    expose:
    - "3306"
    restart: always
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_ROOT=$DB_ROOT
  
  wordpress:
    container_name: wordpress
    image: wordpress
    networks: 
    - inception
    volumes:
    - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on :
    - mariadb
    restart: always
    env_file: .env
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_ROOT=$DB_ROOT
      - ADMIN_USER=$ADMIN_USER
      - ADMIN_PASS=$ADMIN_PASS
      - DOMAINE_NAME=$DOMAINE_NAME
      - WP_USER=$WP_USER
      - WP_PASS=$WP_PASS

volumes:
  wordpress:
    driver : local
    driver_opts:
      type: none
      device: /home/raaga/data/wordpress
      o: bind 
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/raaga/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge

