version: "3.7"

services :
  nginx:
    container_name: nginx
    networks:
    - inception
    volumes:
    - wordpress:/var/www/wordpress
    depends_on:
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    expose:
    - "3306"
    restart: always
    environment:
      - MYSQL_DATABASE="$DATABASE_NAME"
      - USERNAME="$USERNAME"
      - PASSWORD="$PASSWORD"
      - MYSQL_USER="$ADMIN_USER"
      - MYSQL_ROOT_PASSWORD="$ADMIN_PASS"
      - DOMAIN_NAME="$DOMAIN_NAME"
      - WP_USER="$WP_USER"
      - WP_PASS="$WP_PASS"
  
  wordpress:
    container_name: wordpress
    networks: 
    - inception
    volumes:
    - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on :
    - mariadb
    restart: always
    env_file: .env
    environment:
      - USERNAME="$USERNAME"
      - DATABASE_NAME="$DATABASE_NAME"
      - PASSWORD="$PASSWORD"
      - ADMIN_USER="$ADMIN_USER"
      - ADMIN_PASS="$ADMIN_PASS"
      - DOMAIN_NAME="$DOMAIN_NAME"
      - WP_USER="$WP_USER"
      - WP_PASS="$WP_PASS"


volumes:
  wordpress:
    driver : local
    driver_opts:
      type: none
      device: /home/ramsy/data/wordpress
      o: bind 
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ramsy/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge

